M48
; DRILL file {KiCad 9.0.0} date 2026-03-08T15:51:35+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-08T15:51:35+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.500
%
G90
G05
T1
X212.08Y-145.46
X217.08Y-145.46
T2
X139.49Y-95.2
T3
X143.99Y-95.2
T4
X219.46Y-113.46
M30
