M48
; DRILL file {KiCad 9.0.7} date 2026-04-11T12:24:58+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-11T12:24:58+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.500
%
G90
G05
T1
X145.725Y-120.45
X150.725Y-120.45
T2
X208.55Y-95.345
T3
X204.05Y-95.345
T4
X177.48Y-118.825
M30
